/** @format */

import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import GlobalThemeProvider from "@/components/providers/GlobalThemeProvider";

const font = Quicksand({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={font.className}>
				<GlobalThemeProvider>
					<Navbar />
					{children}
				</GlobalThemeProvider>
			</body>
		</html>
	);
}
